import Head from 'next/head'
import Image from 'next/image'

// import styles from '@/styles/Home.module.css'
import Hearnic from '@/components/Home'
import About from '@/components/About'
import Gallery from '@/components/Gallery'
import Services from '@/components/Services'
import Doctors from '@/components/Doctors'
import Review from '@/components/Review'
import Clinic from '@/components/Clinic'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <Hearnic />
        <About />
        <Gallery /> */}
        {/* <Doctors /> */}
        {/* <Services /> */}
        {/* <Review /> */}
        <Clinic />
      </main>
    </>
  )
}
